-- Normalise repeated text values into lookup tables + id-to-id join tables.
--
-- Every table below stores a short string that repeats hundreds of thousands of
-- times (formtag.tag repeats ~1,000,000x). Replacing that text with a 4-byte
-- integer FK removes the repetition and turns each *Tag / *Category table into a
-- genuine many-to-many junction.
--
--   Tag(id, name)                     shared by 6 tag tables
--   Category(id, name)                shared by 2 category tables
--   FormTag(form_id, tag_id)          <- was (form_id, tag TEXT)
--   SenseCategory(sense_id, category_id)  <- was (sense_id, name TEXT)
--   ...and so on
--
-- The tag vocabularies of the six *Tag tables only partly overlap (7-36%
-- pairwise), but their union is far smaller than their sum, and one shared
-- vocabulary means "find everything tagged 'plural'" is a single join instead
-- of six. Categories are shared for the same reason (~45% overlap).
--
-- HOW TO RUN
--   psql -d wiktionary -f normalize_postgres.sql
--
-- This rewrites ~460 million rows and needs free disk roughly equal to the
-- tables being rebuilt (each CREATE TABLE AS writes a new copy before the old
-- one is dropped). Budget for that before starting. Run it in a screen/tmux
-- session; it is not quick.
--
-- Each section is independent and idempotent-ish: it builds <table>_new, swaps
-- it in, and drops the old table. If you stop partway, finished sections stay
-- done. Sections are ordered cheapest-first so you can stop early and still
-- have banked most of the win per hour spent.
--
-- SAFETY: this DROPs the original tables. Take a backup, or run section by
-- section and verify the row counts printed by each \echo before continuing.

\timing on
\set ON_ERROR_STOP on

-- ---------------------------------------------------------------------------
-- 1. Shared vocabularies
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS Tag (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Category (
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

-- Collect every distinct tag from all six tag tables in one pass each.
INSERT INTO Tag (name)
SELECT DISTINCT tag FROM (
    SELECT tag FROM FormTag          WHERE tag IS NOT NULL
    UNION SELECT tag FROM SenseTag         WHERE tag IS NOT NULL
    UNION SELECT tag FROM SoundTag         WHERE tag IS NOT NULL
    UNION SELECT tag FROM WordRelationTag  WHERE tag IS NOT NULL
    UNION SELECT tag FROM TranslationTag   WHERE tag IS NOT NULL
    UNION SELECT tag FROM DescendantTag    WHERE tag IS NOT NULL
    UNION SELECT tag FROM SenseRelationTag WHERE tag IS NOT NULL
) t
ON CONFLICT (name) DO NOTHING;

INSERT INTO Category (name)
SELECT DISTINCT name FROM (
    SELECT name FROM SenseCategory WHERE name IS NOT NULL
    UNION SELECT name FROM WordCategory  WHERE name IS NOT NULL
) t
ON CONFLICT (name) DO NOTHING;

\echo '--- vocabulary sizes ---'
SELECT 'Tag' AS lookup, count(*) FROM Tag
UNION ALL SELECT 'Category', count(*) FROM Category;

-- ---------------------------------------------------------------------------
-- 2. Junction tables, smallest first
--
-- CREATE TABLE AS + swap is used rather than ALTER TABLE ... USING because the
-- latter rewrites the table while holding an ACCESS EXCLUSIVE lock and cannot
-- drop the old text column's bloat. is_raw is kept: it distinguishes a
-- normalised tag from a wiktextract raw_tag.
--
-- LEFT JOIN, not JOIN: a row whose tag/name is NULL keeps its place with a NULL
-- tag_id rather than being silently dropped. An inner join here would lose rows
-- without any error, which is exactly the kind of loss you would not notice
-- until much later. Row counts before and after must match exactly.
-- ---------------------------------------------------------------------------

-- SenseRelationTag: ~0.5M rows
CREATE TABLE SenseRelationTag_new AS
SELECT srt.relation_id, t.id AS tag_id, srt.is_raw
FROM SenseRelationTag srt LEFT JOIN Tag t ON t.name = srt.tag;
DROP TABLE SenseRelationTag;
ALTER TABLE SenseRelationTag_new RENAME TO SenseRelationTag;

-- DescendantTag: ~0.8M rows
CREATE TABLE DescendantTag_new AS
SELECT dt.descendant_id, t.id AS tag_id, dt.is_raw
FROM DescendantTag dt LEFT JOIN Tag t ON t.name = dt.tag;
DROP TABLE DescendantTag;
ALTER TABLE DescendantTag_new RENAME TO DescendantTag;

-- TranslationTag: ~1.6M rows
CREATE TABLE TranslationTag_new AS
SELECT tt.translation_id, t.id AS tag_id, tt.is_raw
FROM TranslationTag tt LEFT JOIN Tag t ON t.name = tt.tag;
DROP TABLE TranslationTag;
ALTER TABLE TranslationTag_new RENAME TO TranslationTag;

-- WordRelationTag: ~12.8M rows
CREATE TABLE WordRelationTag_new AS
SELECT wrt.relation_id, t.id AS tag_id, wrt.is_raw
FROM WordRelationTag wrt LEFT JOIN Tag t ON t.name = wrt.tag;
DROP TABLE WordRelationTag;
ALTER TABLE WordRelationTag_new RENAME TO WordRelationTag;

-- SoundTag: ~20.4M rows
CREATE TABLE SoundTag_new AS
SELECT st.sound_id, t.id AS tag_id, st.is_raw
FROM SoundTag st LEFT JOIN Tag t ON t.name = st.tag;
DROP TABLE SoundTag;
ALTER TABLE SoundTag_new RENAME TO SoundTag;

-- WordCategory: ~25.2M rows
CREATE TABLE WordCategory_new AS
SELECT wc.word_id, c.id AS category_id
FROM WordCategory wc LEFT JOIN Category c ON c.name = wc.name;
DROP TABLE WordCategory;
ALTER TABLE WordCategory_new RENAME TO WordCategory;

-- SenseTag: ~34.3M rows
CREATE TABLE SenseTag_new AS
SELECT st.sense_id, t.id AS tag_id, st.is_raw
FROM SenseTag st LEFT JOIN Tag t ON t.name = st.tag;
DROP TABLE SenseTag;
ALTER TABLE SenseTag_new RENAME TO SenseTag;

-- SenseCategory: ~64.5M rows
CREATE TABLE SenseCategory_new AS
SELECT sc.sense_id, c.id AS category_id
FROM SenseCategory sc LEFT JOIN Category c ON c.name = sc.name;
DROP TABLE SenseCategory;
ALTER TABLE SenseCategory_new RENAME TO SenseCategory;

-- FormTag: ~300.7M rows, the big one. Expect this to dominate the runtime.
CREATE TABLE FormTag_new AS
SELECT ft.form_id, t.id AS tag_id, ft.is_raw
FROM FormTag ft LEFT JOIN Tag t ON t.name = ft.tag;
DROP TABLE FormTag;
ALTER TABLE FormTag_new RENAME TO FormTag;

-- ---------------------------------------------------------------------------
-- 3. Indexes and foreign keys
--
-- CREATE TABLE AS carries over no keys or indexes, so they are built here.
-- These are the access paths the tables actually need: owner -> tags, and the
-- reverse tag -> owners.
-- ---------------------------------------------------------------------------

-- No primary key is added. The surrogate id these tables used to carry was
-- referenced by nothing (verified against information_schema), so it cost
-- 3.76 GB of column data plus 10.58 GB of primary-key index to identify rows
-- nobody looked up by id.
--
-- A composite PK on (owner_id, tag_id, is_raw) is NOT used either: the data
-- contains genuine duplicate tuples (descendanttag 11,147, wordrelationtag
-- 1,358, senserelationtag 13), so a unique constraint would fail outright.
-- Dedupe first if you want one -- see the optional section at the end.

-- Owner-side lookups ("give me the tags for this form")
CREATE INDEX ix_senserelationtag ON SenseRelationTag (relation_id);
CREATE INDEX ix_descendanttag    ON DescendantTag (descendant_id);
CREATE INDEX ix_translationtag   ON TranslationTag (translation_id);
CREATE INDEX ix_wordrelationtag  ON WordRelationTag (relation_id);
CREATE INDEX ix_soundtag         ON SoundTag (sound_id);
CREATE INDEX ix_wordcategory     ON WordCategory (word_id);
CREATE INDEX ix_sensetag         ON SenseTag (sense_id);
CREATE INDEX ix_sensecategory    ON SenseCategory (sense_id);
CREATE INDEX ix_formtag          ON FormTag (form_id);

-- Reverse lookups ("give me every sense tagged 'slang'") - this is the direction
-- that was previously a string comparison over tens of millions of rows.
CREATE INDEX ix_sensetag_tag        ON SenseTag (tag_id, sense_id);
CREATE INDEX ix_formtag_tag         ON FormTag (tag_id, form_id);
CREATE INDEX ix_soundtag_tag        ON SoundTag (tag_id, sound_id);
CREATE INDEX ix_sensecategory_cat   ON SenseCategory (category_id, sense_id);
CREATE INDEX ix_wordcategory_cat    ON WordCategory (category_id, word_id);

ALTER TABLE SenseRelationTag ADD CONSTRAINT fk_srt_tag  FOREIGN KEY (tag_id)      REFERENCES Tag (id);
ALTER TABLE DescendantTag    ADD CONSTRAINT fk_dt_tag   FOREIGN KEY (tag_id)      REFERENCES Tag (id);
ALTER TABLE TranslationTag   ADD CONSTRAINT fk_tt_tag   FOREIGN KEY (tag_id)      REFERENCES Tag (id);
ALTER TABLE WordRelationTag  ADD CONSTRAINT fk_wrt_tag  FOREIGN KEY (tag_id)      REFERENCES Tag (id);
ALTER TABLE SoundTag         ADD CONSTRAINT fk_st_tag   FOREIGN KEY (tag_id)      REFERENCES Tag (id);
ALTER TABLE SenseTag         ADD CONSTRAINT fk_sent_tag FOREIGN KEY (tag_id)      REFERENCES Tag (id);
ALTER TABLE FormTag          ADD CONSTRAINT fk_ft_tag   FOREIGN KEY (tag_id)      REFERENCES Tag (id);
ALTER TABLE WordCategory     ADD CONSTRAINT fk_wc_cat   FOREIGN KEY (category_id) REFERENCES Category (id);
ALTER TABLE SenseCategory    ADD CONSTRAINT fk_sc_cat   FOREIGN KEY (category_id) REFERENCES Category (id);

-- ---------------------------------------------------------------------------
-- 4. Compatibility views, so existing queries using the text column still work
-- ---------------------------------------------------------------------------

CREATE OR REPLACE VIEW v_FormTag AS
SELECT ft.form_id, t.name AS tag, ft.is_raw
FROM FormTag ft JOIN Tag t ON t.id = ft.tag_id;

CREATE OR REPLACE VIEW v_SenseTag AS
SELECT st.sense_id, t.name AS tag, st.is_raw
FROM SenseTag st JOIN Tag t ON t.id = st.tag_id;

CREATE OR REPLACE VIEW v_SenseCategory AS
SELECT sc.sense_id, c.name
FROM SenseCategory sc JOIN Category c ON c.id = sc.category_id;

CREATE OR REPLACE VIEW v_WordCategory AS
SELECT wc.word_id, c.name
FROM WordCategory wc JOIN Category c ON c.id = wc.category_id;

-- ---------------------------------------------------------------------------
-- 5. Reclaim and refresh statistics
-- ---------------------------------------------------------------------------

ANALYZE Tag;
ANALYZE Category;
ANALYZE FormTag;
ANALYZE SenseCategory;
ANALYZE SenseTag;
ANALYZE WordCategory;
ANALYZE SoundTag;
ANALYZE WordRelationTag;
ANALYZE TranslationTag;
ANALYZE DescendantTag;
ANALYZE SenseRelationTag;

\echo '--- final sizes ---'
SELECT relname, n_live_tup, pg_size_pretty(pg_total_relation_size(relid)) AS size
FROM pg_stat_user_tables
WHERE relname IN ('formtag','sensecategory','sensetag','wordcategory','soundtag',
                  'wordrelationtag','translationtag','descendanttag',
                  'senserelationtag','tag','category')
ORDER BY n_live_tup DESC;
