-- PostgreSQL schema for the kaikki.org Wiktionary dump.
--
-- Tables and primary keys only. Indexes AND foreign key constraints live in
-- indexes_postgres.sql so the bulk load runs unconstrained; apply that file
-- once the load has finished.
--
-- Identifiers are written in CamelCase for readability. PostgreSQL folds
-- unquoted identifiers to lower case, so the actual objects are "word",
-- "senseexample" and so on.
--
-- glosses_json / raw_glosses_json / bold_text_offsets are TEXT holding JSON so
-- that both backends behave identically. To use native JSON in PostgreSQL:
--   ALTER TABLE Sense ALTER COLUMN glosses_json TYPE JSONB USING glosses_json::jsonb;

CREATE TABLE IF NOT EXISTS Word (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word             TEXT,
    pos              TEXT,
    lang             TEXT,
    lang_code        TEXT,
    etymology_text   TEXT,
    etymology_number TEXT,
    line_number      INTEGER
);

-- Single-row bookmark so an interrupted run can resume in O(1).
CREATE TABLE IF NOT EXISTS Progress (
    id        INTEGER PRIMARY KEY CHECK (id = 1),
    last_line INTEGER NOT NULL
);

-- Lookup for the integer discriminator used by WordRelation / SenseRelation.
CREATE TABLE IF NOT EXISTS RelationType (
    id   SMALLINT PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS WordCategory (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id BIGINT,
    name    TEXT
);

CREATE TABLE IF NOT EXISTS WordWikipedia (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id BIGINT,
    title   TEXT
);

CREATE TABLE IF NOT EXISTS HeadTemplate (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id   BIGINT,
    name      TEXT,
    expansion TEXT
);

CREATE TABLE IF NOT EXISTS EtymologyTemplate (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id   BIGINT,
    name      TEXT,
    expansion TEXT
);

CREATE TABLE IF NOT EXISTS EtymologyTemplateArgs (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etymology_template_id BIGINT,
    arg_key               TEXT,
    arg_value             TEXT
);

CREATE TABLE IF NOT EXISTS Form (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id BIGINT,
    form    TEXT,
    ipa     TEXT,
    roman   TEXT,
    source  TEXT,
    head_nr INTEGER
);

CREATE TABLE IF NOT EXISTS FormTag (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    form_id BIGINT,
    tag     TEXT,
    is_raw  SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Sound (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id   BIGINT,
    ipa       TEXT,
    enpr      TEXT,
    rhymes    TEXT,
    homophone TEXT,
    note      TEXT,
    audio     TEXT,
    ogg_url   TEXT,
    mp3_url   TEXT,
    wav_url   TEXT,
    oga_url   TEXT,
    opus_url  TEXT,
    other     TEXT,
    text      TEXT
);

CREATE TABLE IF NOT EXISTS SoundTag (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sound_id BIGINT,
    tag      TEXT,
    is_raw   SMALLINT DEFAULT 0
);

-- Descendants nest through a `descendants` key; parent_id models that tree and
-- depth is the recursion level (0 for a top-level descendant).
CREATE TABLE IF NOT EXISTS Descendant (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id   BIGINT,
    parent_id BIGINT,
    depth     INTEGER,
    lang      TEXT,
    lang_code TEXT,
    word      TEXT,
    roman     TEXT,
    sense     TEXT
);

CREATE TABLE IF NOT EXISTS DescendantTag (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descendant_id BIGINT,
    tag           TEXT,
    is_raw        SMALLINT DEFAULT 0
);

-- Translations only ever appear at word level in kaikki output.
CREATE TABLE IF NOT EXISTS Translation (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id     BIGINT,
    lang        TEXT,
    lang_code   TEXT,
    code        TEXT,
    sense       TEXT,
    word        TEXT,
    roman       TEXT,
    alt         TEXT,
    english     TEXT,
    translation TEXT,
    note        TEXT,
    taxonomic   TEXT
);

CREATE TABLE IF NOT EXISTS TranslationTag (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    translation_id BIGINT,
    tag            TEXT,
    is_raw         SMALLINT DEFAULT 0
);

-- All word-level relations (derived, synonyms, antonyms, hyponyms, ...) in one
-- table, discriminated by relation_type. See RelationType and v_WordRelation.
CREATE TABLE IF NOT EXISTS WordRelation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id       BIGINT,
    relation_type SMALLINT,
    word          TEXT,
    sense         TEXT,
    source        TEXT,
    english       TEXT,
    roman         TEXT,
    alt           TEXT,
    qualifier     TEXT,
    taxonomic     TEXT
);

CREATE TABLE IF NOT EXISTS WordRelationTag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT,
    tag         TEXT,
    is_raw      SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Sense (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    word_id          BIGINT,
    sense_index      INTEGER,
    gloss            TEXT,
    glosses_json     TEXT,
    raw_glosses_json TEXT,
    qualifier        TEXT
);

-- is_raw = 0 for normalised tags, 1 for wiktextract raw_tags.
CREATE TABLE IF NOT EXISTS SenseTag (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT,
    tag      TEXT,
    is_raw   SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS SenseTopic (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT,
    topic    TEXT
);

CREATE TABLE IF NOT EXISTS SenseCategory (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT,
    name     TEXT
);

CREATE TABLE IF NOT EXISTS SenseLink (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT,
    text     TEXT,
    target   TEXT
);

CREATE TABLE IF NOT EXISTS SenseExample (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id          BIGINT,
    text              TEXT,
    ref               TEXT,
    type              TEXT,
    english           TEXT,
    translation       TEXT,
    roman             TEXT,
    literal_meaning   TEXT,
    note              TEXT,
    bold_text_offsets TEXT
);

CREATE TABLE IF NOT EXISTS SenseFormOf (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT,
    word     TEXT,
    extra    TEXT
);

CREATE TABLE IF NOT EXISTS SenseAltOf (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT,
    word     TEXT,
    extra    TEXT
);

CREATE TABLE IF NOT EXISTS SenseWikidata (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id BIGINT,
    code     TEXT
);

CREATE TABLE IF NOT EXISTS SenseRelation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sense_id      BIGINT,
    relation_type SMALLINT,
    word          TEXT,
    sense         TEXT,
    source        TEXT,
    english       TEXT,
    roman         TEXT,
    alt           TEXT,
    taxonomic     TEXT
);

CREATE TABLE IF NOT EXISTS SenseRelationTag (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id BIGINT,
    tag         TEXT,
    is_raw      SMALLINT DEFAULT 0
);

INSERT INTO RelationType (id, name) VALUES
    (0,  'derived'),
    (1,  'synonyms'),
    (2,  'antonyms'),
    (3,  'hypernyms'),
    (4,  'hyponyms'),
    (5,  'meronyms'),
    (6,  'holonyms'),
    (7,  'coordinate_terms'),
    (8,  'related'),
    (9,  'troponyms'),
    (10, 'proverbs'),
    (11, 'instances'),
    (12, 'abbreviations')
ON CONFLICT (id) DO NOTHING;

CREATE OR REPLACE VIEW v_WordRelation AS
SELECT wr.id, wr.word_id, rt.name AS relation, wr.word, wr.sense,
       wr.source, wr.english, wr.roman, wr.alt, wr.qualifier, wr.taxonomic
FROM WordRelation wr JOIN RelationType rt ON rt.id = wr.relation_type;

CREATE OR REPLACE VIEW v_SenseRelation AS
SELECT sr.id, sr.sense_id, rt.name AS relation, sr.word, sr.sense,
       sr.source, sr.english, sr.roman, sr.alt, sr.taxonomic
FROM SenseRelation sr JOIN RelationType rt ON rt.id = sr.relation_type;
